/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.theme.backgroundImage'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.theme.backgroundImage'
  image: l.BlobRef
  width?: number
  repeat?: boolean
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    image: l.blob({
      accept: ['image/*'],
      maxSize: 1000000,
      allowLegacy: false,
    }),
    width: l.optional(l.integer()),
    repeat: l.optional(l.boolean()),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
