/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.theme.color'

export { $nsid }

type Rgb = {
  $type?: 'pub.leaflet.theme.color#rgb'
  b: number
  g: number
  r: number
}

export type { Rgb }

const rgb = l.typedObject<Rgb>(
  $nsid,
  'rgb',
  l.object({
    b: l.integer({ maximum: 255, minimum: 0 }),
    g: l.integer({ maximum: 255, minimum: 0 }),
    r: l.integer({ maximum: 255, minimum: 0 }),
  }),
)

export { rgb }

type Rgba = {
  $type?: 'pub.leaflet.theme.color#rgba'
  a: number
  b: number
  g: number
  r: number
}

export type { Rgba }

const rgba = l.typedObject<Rgba>(
  $nsid,
  'rgba',
  l.object({
    a: l.integer({ maximum: 100, minimum: 0 }),
    b: l.integer({ maximum: 255, minimum: 0 }),
    g: l.integer({ maximum: 255, minimum: 0 }),
    r: l.integer({ maximum: 255, minimum: 0 }),
  }),
)

export { rgba }
