/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.iframe'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.iframe'
  url: l.UriString
  height?: number
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    url: l.string({ format: 'uri' }),
    height: l.optional(l.integer({ maximum: 1600, minimum: 16 })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
