/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.image'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.image'

  /**
   * Alt text description of the image, for accessibility.
   */
  alt?: string
  image: l.BlobRef
  aspectRatio: AspectRatio
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    alt: l.optional(l.string()),
    image: l.blob({
      accept: ['image/*'],
      maxSize: 1000000,
      allowLegacy: false,
    }),
    aspectRatio: l.ref<AspectRatio>((() => aspectRatio) as any),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

type AspectRatio = {
  $type?: 'pub.leaflet.blocks.image#aspectRatio'
  width: number
  height: number
}

export type { AspectRatio }

const aspectRatio = l.typedObject<AspectRatio>(
  $nsid,
  'aspectRatio',
  l.object({ width: l.integer(), height: l.integer() }),
)

export { aspectRatio }
