/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.ts'

const $nsid = 'pub.leaflet.blocks.poll'

export { $nsid }

type Main = { $type?: 'pub.leaflet.blocks.poll'; pollRef: RepoStrongRef.Main }

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    pollRef: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
