/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BlocksText from './text.defs.ts'
import * as BlocksHeader from './header.defs.ts'
import * as BlocksImage from './image.defs.ts'

const $nsid = 'pub.leaflet.blocks.unorderedList'

export { $nsid }

type Main = { $type?: 'pub.leaflet.blocks.unorderedList'; children: ListItem[] }

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({ children: l.array(l.ref<ListItem>((() => listItem) as any)) }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

type ListItem = {
  $type?: 'pub.leaflet.blocks.unorderedList#listItem'
  content:
    | l.TypedRef<BlocksText.Main>
    | l.TypedRef<BlocksHeader.Main>
    | l.TypedRef<BlocksImage.Main>
    | l.TypedObject
  children?: ListItem[]
}

export type { ListItem }

const listItem = l.typedObject<ListItem>(
  $nsid,
  'listItem',
  l.object({
    content: l.typedUnion(
      [
        l.typedRef<BlocksText.Main>((() => BlocksText.main) as any),
        l.typedRef<BlocksHeader.Main>((() => BlocksHeader.main) as any),
        l.typedRef<BlocksImage.Main>((() => BlocksImage.main) as any),
      ],
      false,
    ),
    children: l.optional(l.array(l.ref<ListItem>((() => listItem) as any))),
  }),
)

export { listItem }
