/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'pub.leaflet.blocks.website'

export { $nsid }

type Main = {
  $type?: 'pub.leaflet.blocks.website'
  src: l.UriString
  title?: string
  description?: string
  previewImage?: l.BlobRef
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    src: l.string({ format: 'uri' }),
    title: l.optional(l.string()),
    description: l.optional(l.string()),
    previewImage: l.optional(
      l.blob({ accept: ['image/*'], maxSize: 1000000, allowLegacy: false }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
