/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as BlocksIframe from '../blocks/iframe.defs.ts'
import * as BlocksText from '../blocks/text.defs.ts'
import * as BlocksBlockquote from '../blocks/blockquote.defs.ts'
import * as BlocksHeader from '../blocks/header.defs.ts'
import * as BlocksImage from '../blocks/image.defs.ts'
import * as BlocksUnorderedList from '../blocks/unorderedList.defs.ts'
import * as BlocksWebsite from '../blocks/website.defs.ts'
import * as BlocksMath from '../blocks/math.defs.ts'
import * as BlocksCode from '../blocks/code.defs.ts'
import * as BlocksHorizontalRule from '../blocks/horizontalRule.defs.ts'
import * as BlocksBskyPost from '../blocks/bskyPost.defs.ts'
import * as BlocksPage from '../blocks/page.defs.ts'
import * as BlocksPoll from '../blocks/poll.defs.ts'
import * as BlocksButton from '../blocks/button.defs.ts'

const $nsid = 'pub.leaflet.pages.canvas'

export { $nsid }

type Main = { $type?: 'pub.leaflet.pages.canvas'; id?: string; blocks: Block[] }

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    id: l.optional(l.string()),
    blocks: l.array(l.ref<Block>((() => block) as any)),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main)

type Block = {
  $type?: 'pub.leaflet.pages.canvas#block'
  x: number
  y: number
  block:
    | l.TypedRef<BlocksIframe.Main>
    | l.TypedRef<BlocksText.Main>
    | l.TypedRef<BlocksBlockquote.Main>
    | l.TypedRef<BlocksHeader.Main>
    | l.TypedRef<BlocksImage.Main>
    | l.TypedRef<BlocksUnorderedList.Main>
    | l.TypedRef<BlocksWebsite.Main>
    | l.TypedRef<BlocksMath.Main>
    | l.TypedRef<BlocksCode.Main>
    | l.TypedRef<BlocksHorizontalRule.Main>
    | l.TypedRef<BlocksBskyPost.Main>
    | l.TypedRef<BlocksPage.Main>
    | l.TypedRef<BlocksPoll.Main>
    | l.TypedRef<BlocksButton.Main>
    | l.TypedObject
  width: number
  height?: number

  /**
   * The rotation of the block in degrees
   */
  rotation?: number
}

export type { Block }

const block = l.typedObject<Block>(
  $nsid,
  'block',
  l.object({
    x: l.integer(),
    y: l.integer(),
    block: l.typedUnion(
      [
        l.typedRef<BlocksIframe.Main>((() => BlocksIframe.main) as any),
        l.typedRef<BlocksText.Main>((() => BlocksText.main) as any),
        l.typedRef<BlocksBlockquote.Main>((() => BlocksBlockquote.main) as any),
        l.typedRef<BlocksHeader.Main>((() => BlocksHeader.main) as any),
        l.typedRef<BlocksImage.Main>((() => BlocksImage.main) as any),
        l.typedRef<BlocksUnorderedList.Main>(
          (() => BlocksUnorderedList.main) as any,
        ),
        l.typedRef<BlocksWebsite.Main>((() => BlocksWebsite.main) as any),
        l.typedRef<BlocksMath.Main>((() => BlocksMath.main) as any),
        l.typedRef<BlocksCode.Main>((() => BlocksCode.main) as any),
        l.typedRef<BlocksHorizontalRule.Main>(
          (() => BlocksHorizontalRule.main) as any,
        ),
        l.typedRef<BlocksBskyPost.Main>((() => BlocksBskyPost.main) as any),
        l.typedRef<BlocksPage.Main>((() => BlocksPage.main) as any),
        l.typedRef<BlocksPoll.Main>((() => BlocksPoll.main) as any),
        l.typedRef<BlocksButton.Main>((() => BlocksButton.main) as any),
      ],
      false,
    ),
    width: l.integer(),
    height: l.optional(l.integer()),
    rotation: l.optional(l.integer()),
  }),
)

export { block }

type Quote = {
  $type?: 'pub.leaflet.pages.canvas#quote'
  end: Position
  start: Position
}

export type { Quote }

const quote = l.typedObject<Quote>(
  $nsid,
  'quote',
  l.object({
    end: l.ref<Position>((() => position) as any),
    start: l.ref<Position>((() => position) as any),
  }),
)

export { quote }

type Position = {
  $type?: 'pub.leaflet.pages.canvas#position'
  block: number[]
  offset: number
}

export type { Position }

const position = l.typedObject<Position>(
  $nsid,
  'position',
  l.object({ block: l.array(l.integer()), offset: l.integer() }),
)

export { position }

type TextAlignLeft = 'pub.leaflet.pages.canvas#textAlignLeft'

export type { TextAlignLeft }

const textAlignLeft = l.token($nsid, 'textAlignLeft')

export { textAlignLeft }

type TextAlignRight = 'pub.leaflet.pages.canvas#textAlignRight'

export type { TextAlignRight }

const textAlignRight = l.token($nsid, 'textAlignRight')

export { textAlignRight }

type TextAlignCenter = 'pub.leaflet.pages.canvas#textAlignCenter'

export type { TextAlignCenter }

const textAlignCenter = l.token($nsid, 'textAlignCenter')

export { textAlignCenter }
